### ISSUE TITLE
Compile error: schedule

### ISSUE THREAD

**Issue by Dasio** [alexandre-normand/slackscot#141]
# Describe the bug
Can't download latest slackscot because of compile error:
```go
go get -u github.com/alexandre-normand/slackscot
                       
go: finding golang.org/x/sys latest
go: finding github.com/marcsantiago/gocron latest
# github.com/alexandre-normand/slackscot/schedule
../../../go/pkg/mod/github.com/alexandre-normand/slackscot@v1.37.1/schedule/schedule.go:167:17: cannot use false (type bool) as type func(*gocron.Job) in argument to s.Every
```
## Version
`Slackscot` version: v1.37.1

## To Reproduce
1. `go get -u github.com/alexandre-normand/slackscot` in your bot project

## Expected behavior
It should compile

## Anything you'd like to add
It's weird because I can't see any changes regarding this functionality nor in gocron. And it was working for me yesterday with 1.37.0

https://github.com/marcsantiago/gocron/blob/master/gocron.go#L467
There is no boolean parameter.

**Comment by Dasio** [comment]
This is the commit which broke it https://github.com/marcsantiago/gocron/commit/c18ed510c036a921af7f394d6f5bbe2ae36a2db6#diff-b2ff24af043be5594c68ddf66a8eecab

**Comment by alexandre-normand** [comment]
@Dasio I'm not sure I would consider the build broken. Building `slackscot` with its dependencies as specified in `go.mod` works fine. The breakage is because you're doing `go get -u` which tries to updates all dependencies to their latest versions. If you do `go get github.com/alexandre-normand/slackscot` (without `-u`), you should get `v1.37.1` with its pinned dependencies. 

That said, I looked at the changes to `gocron` and the API breaking changes aren't difficult to fix and it would be worthwhile to update the slackscot dependency especially since they now have it officially supporting go modules. I'll do that later today.

**Comment by alexandre-normand** [comment]
I upgraded `gocron` to `v0.0.0-20190722153955-d98f98b8d54e` and changed it to use its latest public API. The latest version with the upgrade is tagged as [v1.37.2](https://github.com/alexandre-normand/slackscot/tree/v1.37.2).

**Comment by Dasio** [comment]
Sorry my bad, I wanted just upgrade slackscot.
